# Generated by Django 3.1.7 on 2021-04-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_comlete',
            field=models.BooleanField(default=False),
        ),
    ]
