# Generated by Django 3.1.7 on 2021-04-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_is_comlete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_comlete',
            new_name='is_complete',
        ),
    ]
